language: python

matrix:
    include:
        - python: "3.5"
          arch : ppc64le
          os: linux
          dist: xenial
        - python: "3.6"
          arch : ppc64le
          os: linux
          dist: bionic
        - python: "3.7"
          arch : ppc64le
          os: linux
          dist: bionic
        - python: "3.8"
          arch : ppc64le
          os: linux
          dist: focal
        - python: "3.9"
          arch : ppc64le
          os: linux
          dist: focal

addons:
  apt:
    packages:
    - libattr1-dev
    - pkg-config
    - gcc
    - libfuse-dev

install: test/ci-install.sh

script: test/ci-test.sh
